def raise_exception():
    print("Exception has been raised")

    